FROM oven/bun:1.2.10-alpine AS builder

WORKDIR /app

COPY package.json bun.lock tsconfig.json ./

RUN bun install --frozen-lockfile

COPY ./src ./src

RUN bun run build

FROM oven/bun:1.2.10-alpine

WORKDIR /app

COPY --from=builder /app/dist/index.js ./index.js

CMD [ "bun", "index.js" ]
