FROM oven/bun:1.2.10-alpine AS builder

WORKDIR /app

COPY package.json bun.lock tsconfig.json ./

RUN bun install --frozen-lockfile

COPY ./src ./src

RUN bun run build

RUN bun run compile-styles

FROM oven/bun:1.2.10-alpine

WORKDIR /app

COPY --from=builder /app/dist/server.js ./server.js
COPY --from=builder /app/dist/client.js ./dist/client.js
COPY --from=builder /app/dist/styles.css ./dist/styles.css

ENV NODE_ENV=production

CMD [ "bun", "server.js" ]
